### ISSUE TITLE
Make setup instructions a little clearer

### ISSUE THREAD

**Issue by greg3k** [ryancurrah/synology-notifications#3]
Hello,

Really appreciate you taking the time to make this.
Slack is really a better/more modern choice for these notifications.

I was able to get it setup and working correctly.
But it seems the setup instructions you provided aren't formatted correctly.

Really it was just important that (and to anyone that may read this):
the `api_key` field goes under  `HTTP Request Header`

and then under `HTTP request body`:

`phone_number`
`message=hello world`

**Comment by ryancurrah** [comment]
I updated the README to fix the formatting. Does that look better?

**Comment by greg3k** [comment]
Yes, thank you.
