### ISSUE TITLE
Does it still work? | dial tcp 13.225.85.153:443: i/o timeout

### ISSUE THREAD

**Issue by aHVzY2g** [ryancurrah/synology-notifications#4]
Hey guys,

I just would like to know if the docker container still works, because I get an timeout error? 
`2020/03/03 20:15:59 error sendming slack message: failed to post webhook: Post https://hooks.slack.com/services/xxxxxxx/xxxxxxxxxx/xxxxxxxxxxxxxxx: dial tcp 13.225.85.153:443: i/o timeout `
I am able to ping the ip address just fine.

**Comment by ryancurrah** [comment]
It works for me atm. Were you able to resolve this?

**Comment by aHVzY2g** [comment]
So far I wasn't able to resolve it. Right now I use a small PHP script to achieve the same thing. 
As it's working for you I will close this Issue. If you want to Investigate, fell free to open it again :D
