### ISSUE TITLE
Blank message in Slack

### ISSUE THREAD

**Issue by fedor-git** [ryancurrah/synology-notifications#5]
Hi. I use docker container, have issue when send test message in Slack. It sent message OK but in Slack i got blank message.

**Comment by ryancurrah** [comment]
I've added screenshots to the readme, ensure you have set it up similar.

**Comment by ryancurrah** [comment]
https://github.com/ryancurrah/synology-notifications#setting-up-synology-with-screenshots

**Comment by rmaronson** [comment]
Just ran into this too -- issue is that the message body has to be sent in request body, not header, which isn't clear from the instructions (but is from the screenshots). Maybe worth updating the text too; either way, thanks for this!

**Comment by ryancurrah** [comment]
Thanks @rmaronson I updated the readme to be more clear. Closing this issue.
