### ISSUE TITLE
invalid api key 

### ISSUE THREAD

**Issue by ghost** [ryancurrah/synology-notifications#6]
Hello ryancurrah,

Thanks for your work on this feature.
I have a issue, when i send test notification from synology to slack, i don't receive it on slack.
On my ubuntu vm where i run the docker i have the following error (invalid api key): 
docker run -p 8080:8080 -e API_KEY='LO45UXS%amLAWJn6CwJ1koaXW&7pY9#Z' -e SLACK_WEBHOOK='https://hooks.slack.com/services/T02UNCY9H/B011ZGHRKQV/xxxxxxxxxxxxxxxxx' ryancurrah/synology-notifications:latest

Below the screenshot of my terminal:
![image](https://user-images.githubusercontent.com/63454578/80198158-f6be5b80-861f-11ea-8d50-35a0d56b2282.png)

My api_key is the same on synology and on the command i run.
I have also try with export API_KEY command.

Do you know how can i fix this issue ?
Thanks.

**Comment by ryancurrah** [comment]
Are you sure you put in the right api key on synology? Or you named the header correctly?

Try using curl to test the service...

```
curl -H 'api_key: LO45UXS%amLAWJn6CwJ1koaXW&7pY9#Z' -X POST 'http://127.0.0.1:8080' -d '{"message": "hello world"}'
```

**Comment by ghost** [comment]
Hello @ryancurrah ,

The curl is working. I'm getting the message on slack.
I have check my synology setting and i have seen that i made a mistake on api_key parameter, that's for why it was not working. Now everything works well.
Thanks for your help.
Have a nice week-end !

**Comment by ryancurrah** [comment]
Glad it’s working!
