### ISSUE TITLE
Slack message colour

### ISSUE THREAD

**Issue by tborychowski** [ryancurrah/synology-notifications#7]
Hi,

Thanks a lot for this fantastic project!

Would it be possible to have a configured colour instead of the [hard-coded "warning"](https://github.com/ryancurrah/synology-notifications/blob/master/main.go#L54)?

e.g. my only message from synology is that the backup was successful, but it is displayed in Slack with a yellow warning colour.

**Comment by ryancurrah** [comment]
Hey @tborychowski thanks for your interest. I have pushed a change that allows you to chose the color. The setting is called `SLACK_ATTACHMENT_COLOR ` and you put in a hex color value `#34eb4f`.

**Comment by tborychowski** [comment]
Thank you so much! That's brilliant!
edit: and works perfectly!
